name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'test'
      
jobs:
  docker_build_prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Azure Container Registry
        uses: docker/login-action@v1 
        with:
          registry: aaconreg.azurecr.io
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            aaconreg.azurecr.io/sample_java_app:latest
            aaconreg.azurecr.io/sample_java_app:1.0.0

  docker_build_dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Azure Container Registry
        uses: docker/login-action@v1 
        with:
          registry: aaconreg.azurecr.io
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            aaconreg.azurecr.io/sample_java_app:dev

  docker_build_test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Azure Container Registry
        uses: docker/login-action@v1 
        with:
          registry: aaconreg.azurecr.io
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            aaconreg.azurecr.io/sample_java_app:test

# test
